mvn package

./bin/spark-submit --class bigdata.project.spark.MaxVote --master local[2] /Users/baopham/Documents/workspace/MaxVote/target/MaxVote-0.0.1-SNAPSHOT.jar /Users/baopham/Documents/workspace/MaxVote/data/input.txt /Users/baopham/Documents/workspace/MaxVote/output